name: nsw
version: git
summary: Configurable webserver for snap
description: >
  Built with Ubuntu Core in mind.
  NodeSnapWeb (nsw) allows you to start a node.js file with HTTP support (and maybe more in the future).
  It may even allow you to run a headless server.
  Use the --port and --path options when using the start subcommand,
  and --file when using the run subcommand.
confinement: strict
parts:
  nsw:
    plugin: nodejs
    source: https://github.com/bleonard252/NodeSnapWeb.git
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: armhf
    run-on: armhf
  - build-on: i386
    run-on: i386
  - build-on: arm64
    run-on: arm64
apps:
  nsw:
    command: node /snap/nsw/current/lib/node_modules/nsw/index.js
    plugs:
      - home
      - network
      - network-bind
  npm:
    command: npm
    plugs:
      - home
      - network
      - network-bind
  node:
    command: node
    plugs:
      - home
      - network
      - network-bind
